/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellExchangeRouteImport } from './routes/sell-exchange'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarsSlugRouteImport } from './routes/cars.$slug'

const SellExchangeRoute = SellExchangeRouteImport.update({
  id: '/sell-exchange',
  path: '/sell-exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/cars/$slug',
  path: '/cars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/sell-exchange': typeof SellExchangeRoute
  '/cars/$slug': typeof CarsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/sell-exchange': typeof SellExchangeRoute
  '/cars/$slug': typeof CarsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/finance': typeof FinanceRoute
  '/sell-exchange': typeof SellExchangeRoute
  '/cars/$slug': typeof CarsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collection'
    | '/contact'
    | '/finance'
    | '/sell-exchange'
    | '/cars/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collection'
    | '/contact'
    | '/finance'
    | '/sell-exchange'
    | '/cars/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collection'
    | '/contact'
    | '/finance'
    | '/sell-exchange'
    | '/cars/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  FinanceRoute: typeof FinanceRoute
  SellExchangeRoute: typeof SellExchangeRoute
  CarsSlugRoute: typeof CarsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sell-exchange': {
      id: '/sell-exchange'
      path: '/sell-exchange'
      fullPath: '/sell-exchange'
      preLoaderRoute: typeof SellExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/cars/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  FinanceRoute: FinanceRoute,
  SellExchangeRoute: SellExchangeRoute,
  CarsSlugRoute: CarsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
